### ISSUE TITLE
for use with .tex files

### ISSUE THREAD

**Issue by bookbinder** [jc-doyle/cmp-pandoc-references#4]
This is a great plugin. I’ve been looking for just this thing to use with LaTeX. Unfortunately, though, I can’t use YAML headers with tex files, so I can’t use the plugin. Is there a way around this? Thanks a lot.

**Comment by khaveesh** [comment]
I use `texlab` LSP server for autocompletion with LaTeX files. You should try it out, it is a great plugin.
[https://github.com/latex-lsp/texlab](url)

**Comment by bookbinder** [comment]
I can just comment out the header
